<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    public function run()
    {
        // Categories
        $categories = [
            ['name' => 'SOEP'],
            ['name' => 'VOORGERECHTEN'],
            ['name' => 'MIHOEN GERECHTEN'],
            ['name' => 'CHINESE BAMIGERECHTEN'],
            ['name' => 'INDISCHE GERECHTEN'],
            ['name' => 'EIERGERECHTEN (met witte rijst)'],
            ['name' => 'GROENTEN GERECHTEN (met witte rijst)'],
            ['name' => 'VLEES GERECHTEN (met witte rijst)'],
            ['name' => 'KIPGERECHTEN (met witte rijst)'],
            ['name' => 'GARNALEN GERECHTEN (met witte rijst)'],
        ];

        DB::table('category')->insert($categories);

        // Dishes
        $dishes = [
            ['category_id' => 1, 'menu_number' => '1', 'name' => 'Soep Ling Fa', 'price' => 3.80, 'image' => null],
            ['category_id' => 1, 'menu_number' => '2', 'name' => 'Kippensoep', 'price' => 2.90, 'image' => null],
            ['category_id' => 1, 'menu_number' => '3', 'name' => 'Tomaten soep', 'price' => 2.90, 'image' => null],
            ['category_id' => 1, 'menu_number' => '4', 'name' => 'Haanewijnensoep', 'price' => 3.10, 'image' => null],
            ['category_id' => 1, 'menu_number' => '5', 'name' => 'Champignonsoep', 'price' => 3.30, 'image' => null],
            ['category_id' => 1, 'menu_number' => '6', 'name' => 'Pekings oep', 'price' => 3.80, 'image' => null],
            ['category_id' => 1, 'menu_number' => '7', 'name' => 'Wan Tan Soep', 'price' => 4.30, 'image' => null],
            ['category_id' => 1, 'menu_number' => '8', 'name' => 'Chinese Champignonsoep', 'price' => 4.10, 'image' => null],
            ['category_id' => 2, 'menu_number' => '10', 'name' => 'Loempia Ling Fa (met ajar ananas en pindasaus)', 'price' => 6.20, 'image' => null],
            ['category_id' => 2, 'menu_number' => '11', 'name' => 'Loempia Compleet (met gemoord rundvlees en pikante saus)', 'price' => 6.20, 'image' => null],
            ['category_id' => 2, 'menu_number' => '12', 'name' => 'Loempia met kip', 'price' => 3.80, 'image' => null],
            ['category_id' => 2, 'menu_number' => '14', 'name' => 'Chinese mini loempia (4 st.)', 'price' => 4.90, 'image' => null],
            ['category_id' => 2, 'menu_number' => '15', 'name' => 'Kroepoek', 'price' => 2.50, 'image' => null],
            ['category_id' => 2, 'menu_number' => '16', 'name' => 'Pangsit Goreng (6st.)', 'price' => 3.90, 'image' => null],
            ['category_id' => 2, 'menu_number' => '17', 'name' => 'Chinese Dim Sum', 'price' => 5.40, 'image' => null],
            ['category_id' => 2, 'menu_number' => '20', 'name' => 'Saté Ajam (4st.)', 'price' => 5.40, 'image' => null],
            ['category_id' => 2, 'menu_number' => '21', 'name' => 'Fong Mei Hai (krokant gepancerd garnalen, 4st.)', 'price' => 8.10, 'image' => null],
            ['category_id' => 2, 'menu_number' => '23', 'name' => 'Tsa Siu Mai (gehakken varkensvlees, 4st.)', 'price' => 3.50, 'image' => null],
            ['category_id' => 2, 'menu_number' => '24', 'name' => 'Ajar', 'price' => 3.00, 'image' => null],
            ['category_id' => 2, 'menu_number' => '25', 'name' => 'Witte rijst', 'price' => 3.00, 'image' => null],
            ['category_id' => 2, 'menu_number' => '26', 'name' => 'Groente pindasaus', 'price' => 3.90, 'image' => null],
            ['category_id' => 2, 'menu_number' => '27', 'name' => 'Kleine pindasaus', 'price' => 2.30, 'image' => null],
            ['category_id' => 2, 'menu_number' => '28', 'name' => 'Kippensoep', 'price' => 2.30, 'image' => null],
            ['category_id' => 2, 'menu_number' => '29', 'name' => 'Halve kip', 'price' => 6.00, 'image' => null],
            ['category_id' => 2, 'menu_number' => '29G', 'name' => 'Frikandel', 'price' => 1.40, 'image' => null],
            ['category_id' => 2, 'menu_number' => '180H', 'name' => 'Kleine Sambal', 'price' => 2.50, 'image' => null],
            ['category_id' => 3, 'menu_number' => '30', 'name' => 'Bami of Nasi Gereghtten Ling Fa (foe Yong Hai, Babi Panggang saté en kippensoepje)', 'price' => 14.30, 'image' => null],
            ['category_id' => 3, 'menu_number' => '31', 'name' => 'Bami of Nasi Goreng met ei', 'price' => 5.00, 'image' => null],
            ['category_id' => 3, 'menu_number' => '32', 'name' => 'Bami of Nasi Goreng speciaal', 'price' => 8.50, 'image' => null],
            ['category_id' => 3, 'menu_number' => '33', 'name' => 'Bami of Nasi Goreng met saté (3st.)', 'price' => 8.50, 'image' => null],
            ['category_id' => 3, 'menu_number' => '34', 'name' => 'Nasi Yung Chow', 'price' => 10.90, 'image' => null],
            ['category_id' => 3, 'menu_number' => '35', 'name' => 'Bami of Nasi Malay', 'price' => 9.30, 'image' => null],
            ['category_id' => 3, 'menu_number' => '36', 'name' => 'Bami of Nasi met kipfilet', 'price' => 9.30, 'image' => null],
            ['category_id' => 3, 'menu_number' => '37', 'name' => 'Bami of Nasi met varkensvlees', 'price' => 9.30, 'image' => null],
            ['category_id' => 3, 'menu_number' => '38', 'name' => 'Bami of Nasi met garnalen', 'price' => 14.30, 'image' => null],
            ['category_id' => 3, 'menu_number' => '39', 'name' => 'Bami of Nasi met ossenhaas', 'price' => 15.30, 'image' => null],
            ['category_id' => 4, 'menu_number' => '40', 'name' => 'Babi Panggang Foe Yong Hai en saté', 'price' => 15.80, 'image' => null],
            ['category_id' => 4, 'menu_number' => '41', 'name' => 'Babi Panggang Tap Tjoy en saté', 'price' => 15.80, 'image' => null],
            ['category_id' => 4, 'menu_number' => '42', 'name' => 'Babi Panggang Koe Loe Yuk en saté', 'price' => 15.80, 'image' => null],
            ['category_id' => 4, 'menu_number' => '43', 'name' => 'Babi Panggang Tau Sie Kai en saté', 'price' => 16.50, 'image' => null],
            ['category_id' => 4, 'menu_number' => '44', 'name' => 'Koe Loe Yuk, Foe Yong Hai en saté', 'price' => 15.80, 'image' => null],
            ['category_id' => 4, 'menu_number' => '45', 'name' => 'Koe Loe Yuk, Tap Tjoy en saté', 'price' => 15.80, 'image' => null],
            ['category_id' => 4, 'menu_number' => '46', 'name' => 'Foe Yong Hai, Tap Tjoy en saté', 'price' => 15.80, 'image' => null],
            ['category_id' => 4, 'menu_number' => '47', 'name' => 'Foe Yong Hai, Kip Kerrie en saté', 'price' => 16.50, 'image' => null],
            ['category_id' => 5, 'menu_number' => '50', 'name' => 'Mihoen Ling Fa Panggang saté en kippensoepje)', 'price' => 16.40, 'image' => null],
            ['category_id' => 5, 'menu_number' => '51', 'name' => 'Mihoen met varkensvlees', 'price' => 9.30, 'image' => null],
            ['category_id' => 5, 'menu_number' => '52', 'name' => 'Mihoen met kipfilet', 'price' => 10.40, 'image' => null],
            ['category_id' => 5, 'menu_number' => '53', 'name' => 'Mihoen met ossenhaas', 'price' => 16.40, 'image' => null],
            ['category_id' => 5, 'menu_number' => '54', 'name' => 'Mihoen met garnalen', 'price' => 15.30, 'image' => null],
            ['category_id' => 5, 'menu_number' => '55', 'name' => 'Mihoen Singapore-style', 'price' => 11.90, 'image' => null],
            ['category_id' => 5, 'menu_number' => '56', 'name' => 'Mihoen met Cha Siewvlees en kerrie poeder', 'price' => 11.20, 'image' => null],
            ['category_id' => 6, 'menu_number' => '57', 'name' => 'Chinese Bami Ling Fa', 'price' => 16.40, 'image' => null],
            ['category_id' => 6, 'menu_number' => '58', 'name' => 'Chinese bami met varkensvlees', 'price' => 10.10, 'image' => null],
            ['category_id' => 6, 'menu_number' => '58C', 'name' => 'Chinese Bami met kipfilet', 'price' => 11.20, 'image' => null],
            ['category_id' => 6, 'menu_number' => '58D', 'name' => 'Chinese Bami met garnalen', 'price' => 15.80, 'image' => null],
            ['category_id' => 6, 'menu_number' => '58E', 'name' => 'Chinese Bami met ossenhaas', 'price' => 17.40, 'image' => null],
            ['category_id' => 7, 'menu_number' => 'M1', 'name' => 'Bami of Nasi Rames Ling Fa', 'price' => 15.30, 'image' => null],
            ['category_id' => 7, 'menu_number' => 'M2', 'name' => 'Bami of Nasi Rames', 'price' => 8.80, 'image' => null],
            ['category_id' => 7, 'menu_number' => 'M3', 'name' => 'Bami of Nasi Rames speciaal', 'price' => 10.80, 'image' => null],
            ['category_id' => 7, 'menu_number' => 'M4', 'name' => 'Gado Gado (met witte rijst)', 'price' => 7.60, 'image' => null],
            ['category_id' => 7, 'menu_number' => 'M5', 'name' => 'Daging Smoor (met witte rijst)', 'price' => 13.30, 'image' => null],
            ['category_id' => 7, 'menu_number' => 'M6', 'name' => 'Daging Roedjak (met witte rijst)', 'price' => 13.30, 'image' => null],
            ['category_id' => 8, 'menu_number' => '59', 'name' => 'Foe Yong Hai Ling Fa', 'price' => 16.40, 'image' => null],
            ['category_id' => 8, 'menu_number' => '60', 'name' => 'Foe Yong Hai met varkensvlees', 'price' => 8.80, 'image' => null],
            ['category_id' => 8, 'menu_number' => '61', 'name' => 'Foe Yong Hai met kipfilet', 'price' => 9.20, 'image' => null],
            ['category_id' => 8, 'menu_number' => '62', 'name' => 'Foe Yong Hai met garnalen', 'price' => 15.30, 'image' => null],
            ['category_id' => 8, 'menu_number' => '63', 'name' => 'Foe Yong Hai met crab', 'price' => 15.30, 'image' => null],
            ['category_id' => 8, 'menu_number' => '63A', 'name' => 'Foe Yong Hai met Cha Siew Vlees', 'price' => 11.20, 'image' => null],
            ['category_id' => 8, 'menu_number' => '63B', 'name' => 'Foe Yong Hai met ossenhaas', 'price' => 16.40, 'image' => null],
            ['category_id' => 9, 'menu_number' => '64', 'name' => 'Tap Tjoy Fa', 'price' => 16.40, 'image' => null],
            ['category_id' => 9, 'menu_number' => '65', 'name' => 'Tap Tjoy met kipfilet', 'price' => 8.80, 'image' => null],
            ['category_id' => 9, 'menu_number' => '66', 'name' => 'Tap Tjoy met garnalen', 'price' => 15.30, 'image' => null],
            ['category_id' => 9, 'menu_number' => '67', 'name' => 'Tap Tjoy met ossenhaas', 'price' => 16.40, 'image' => null],
            ['category_id' => 10, 'menu_number' => '70', 'name' => 'Babi Panggang in ketjap saus', 'price' => 12.20, 'image' => null],
            ['category_id' => 10, 'menu_number' => '71', 'name' => 'Babi Panggang in zoetzure saus', 'price' => 12.20, 'image' => null],
            ['category_id' => 10, 'menu_number' => '72', 'name' => 'Cha Siew (rood geroosterde varkensvlees)', 'price' => 13.30, 'image' => null],
            ['category_id' => 10, 'menu_number' => '73', 'name' => 'Cha Siew in pikante saus', 'price' => 13.30, 'image' => null],
            ['category_id' => 10, 'menu_number' => '74', 'name' => 'Koe Loe Yuk (bolletjes vlees met zoetzure saus)', 'price' => 11.90, 'image' => null],
            ['category_id' => 10, 'menu_number' => '75', 'name' => 'Varkenshaas met kerrij saus', 'price' => 11.90, 'image' => null],
            ['category_id' => 10, 'menu_number' => '76', 'name' => 'Varkenshaas met tomatensaus', 'price' => 11.90, 'image' => null],
            ['category_id' => 10, 'menu_number' => '77', 'name' => 'Varkenshaas met champignons in knoflooksaus', 'price' => 11.90, 'image' => null],
            ['category_id' => 10, 'menu_number' => '78', 'name' => 'Varkenshaas met Chinese champignons', 'price' => 12.20, 'image' => null],
            ['category_id' => 10, 'menu_number' => '79', 'name' => 'Varkenshaas met zwarte bonensaus', 'price' => 13.30, 'image' => null],
            ['category_id' => 10, 'menu_number' => '79A', 'name' => 'Varkenshaas met verse ananas in zoetzure saus', 'price' => 13.30, 'image' => null],
            ['category_id' => 10, 'menu_number' => '79B', 'name' => 'Varkenshaas met licht zoet pikante kruiden saus', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '80', 'name' => 'Ajam Panggang in ketjap saus', 'price' => 13.00, 'image' => null],
            ['category_id' => 11, 'menu_number' => '81', 'name' => 'Ajam Panggang in zoetzure saus', 'price' => 13.00, 'image' => null],
            ['category_id' => 11, 'menu_number' => '82', 'name' => 'Kipfilet met kerrie saus', 'price' => 13.00, 'image' => null],
            ['category_id' => 11, 'menu_number' => '83', 'name' => 'Kipfilet met champignons in knoflooksaus', 'price' => 13.00, 'image' => null],
            ['category_id' => 11, 'menu_number' => '84', 'name' => 'Kipfilet met ketjap saus', 'price' => 13.00, 'image' => null],
            ['category_id' => 11, 'menu_number' => '85', 'name' => 'Kipfilet met Chinese champignons', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '86', 'name' => 'Kipfilet met broccoli in knoflooksaus', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '87', 'name' => 'Kipfilet met verse ananas in zoetzure saus', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '89', 'name' => 'Kipfilet met zwarte bonensaus', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '90', 'name' => 'Kipfilet met tomatensaus', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '91', 'name' => 'Tiew Yum Kai (licht gebraden kipfilet met zout en peper)', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '92', 'name' => 'Yak Koe Kai (kipfilet met cashewnoten in licht pikante saus)', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '93', 'name' => 'Yak Koe Kai (kipfilet met lychee in zoetzure saus)', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '94', 'name' => 'Yak Koe Kai (kipfilet met pittige kruiden saus)', 'price' => 13.30, 'image' => null],
            ['category_id' => 11, 'menu_number' => '95', 'name' => 'Yak Koe Kai (kipfilet met cashewnoten in pittige saus)', 'price' => 13.80, 'image' => null],
            ['category_id' => 12, 'menu_number' => '96', 'name' => 'Garnalen met champignons in knoflooksaus', 'price' => 15.90, 'image' => null],
            ['category_id' => 12, 'menu_number' => '97', 'name' => 'Garnalen met ketjap saus', 'price' => 15.90, 'image' => null],
            ['category_id' => 12, 'menu_number' => '98', 'name' => 'Garnalen met tomatensaus', 'price' => 15.90, 'image' => null],
            ['category_id' => 12, 'menu_number' => '99', 'name' => 'Garnalen met Chinese champignons', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '100', 'name' => 'Garnalen met kerrie saus', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '101', 'name' => 'Garnalen met verse bonensaus', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '102', 'name' => 'Garnalen met zwarte pepersaus', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '103', 'name' => 'Garnalen met chilisaus', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '104', 'name' => 'Garnalen met pikante kruiden saus', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '105', 'name' => 'Tiew Yum Haa (garnalen gebakken met zout en peper)', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '106', 'name' => 'Yak Koe Haa (garnalen met cashewnoten in pittige saus)', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '107', 'name' => 'Yak Koe Haa (garnalen met lychee in zoetzure saus)', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '108', 'name' => 'Yak Koe Haa (garnalen met verse ananas in zoetzure saus)', 'price' => 16.10, 'image' => null],
            ['category_id' => 12, 'menu_number' => '109', 'name' => 'Yak Koe Haa (garnalen met pittige kruiden saus)', 'price' => 16.10, 'image' => null],
        ];

        DB::table('dish')->insert($dishes);
    }
}
